### ISSUE TITLE
Error when building the sample using "ELIXIR_MIX_ENV = prod" (in the Makefile)

### ISSUE THREAD

**Issue by mfranck** [botsunit/elixir.mk#1]
The following exception is raised at compile-time: 
Generated iex app
make[1]: Leaving directory `/home/deploy/elixir.mk/sample/deps/elixir'
 DEP    hex
 DEP    poison
- creating /home/deploy/.mix/archives/hex-0.10.1.ez
  make[1]: Entering directory `/home/deploy/elixir.mk/sample/deps/poison'
  Compiled lib/poison.ex
  Compiled lib/poison/decoder.ex
  Compiled lib/poison/parser.ex
  Compiled lib/poison/encoder.ex
  Generated poison app
  *\* (EXIT from #PID<0.47.0>) an exception was raised:
  *\* (UndefinedFunctionError) undefined function Inspect.inspect/2
      (elixir) Inspect.inspect(Poison.Decoder, %Inspect.Opts{base: :decimal, binaries: :infer, char_lists: :infer, limit: 50, pretty: false, safe: true, structs: true, width: 80})
      (elixir) lib/kernel.ex:1569: Kernel.inspect/2
      (mix) lib/mix/tasks/compile.protocols.ex:110: Mix.Tasks.Compile.Protocols.consolidate/3
      (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
      (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
      (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

12:17:35.553 [error] Task #PID<0.194.0> started from #PID<0.47.0> terminating
*\* (UndefinedFunctionError) undefined function Inspect.inspect/2
    (elixir) Inspect.inspect(Poison.Decoder, %Inspect.Opts{base: :decimal, binaries: :infer, char_lists: :infer, limit: 50, pretty: false, safe: true, structs: true, width: 80})
    (elixir) lib/kernel.ex:1569: Kernel.inspect/2
    (mix) lib/mix/tasks/compile.protocols.ex:110: Mix.Tasks.Compile.Protocols.consolidate/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<6.130943846/0 in Mix.Tasks.Compile.Protocols.consolidate/5>
    Args: []

**Comment by mfranck** [comment]
Can be fixed using "ELIXIR_BRANCH=v1.1" in the Makefile
